name: My First workflow


on: [push]

jobs:
    first_job: 
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              
            - name: Welcome message
              run: echo "My First github action"

            - name: List files
              run: ls -a

            - name: Read file
              run: cat README.md
               
